### PR TITLE
2024 Oct 21 - Progress updates for DST

### PR DESCRIPTION
**Pull request by Zorlin**
* Remove unused commitment from index (deployer tool)
* Add specific dates to libp2p eval (binds it to the quarter)
* Add Waku evaluation commitment (restoring recurring regression testing)
* Move debug visualiser dates `ift:visualiser-tool:debug-visualiser`
* Moved the dates for ift:vaclab:better-time-slicing
* Add deliverable reports for waku:waku-evaluation:regression-testing](https://github.com/vacp2p/roadmap/pull/31/commits/fe264bc1d1f1eda30728c34ebabbfd3da20534c9)
* Update status of codex:codex-comparison:matrices-deployments+working-matrices
* Update status of codex:codex-comparison:argocd-or-similar
* Update status to 100% `waku:waku-scaling:test-store-protocol-at-scale`
  * [x] @AlbertoSoutullo Please add deliverables to the PR for this task
 
More to come

### CODE REVIEW

**Comment by Zorlin** [comment]
Added this commit
`Add deliverable reports for waku:waku-evaluation:regression-testing`

Please review @AlbertoSoutullo and see if you think it fits with the timeline :pray:

**Comment by Zorlin** [comment]
Ready4review

**Comment by Zorlin** [comment]
Dropped pre-NCT deliverables after discussion with Alberto.

**Comment by AlbertoSoutullo** [comment]
I think it is not missing anything, so LGTM

**Review by kaiserd — APPROVED** [review]

**Pull request merged**
